MD003: false
MD004:
  style: dash
MD013:
  tables: false
MD026: false
MD029:
  style: one
MD030:
  ul_multi: 1
  ul_single: 1
  ol_multi: 1
  ol_single: 1
MD033: false
MD034: false
MD036: false
MD041: false
