name: Process Issue Open/Edit

on:
  issues:
    types:
      - opened
      - edited

permissions:
  contents: write
  id-token: write
  issues: write

jobs:
  validate:
    name: Process Issue Open/Edit
    runs-on: ubuntu-latest

    if: contains(github.event.issue.labels.*.name, 'gh-intermediate-class')

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Get GitHub App Token
        id: token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.ISSUEOPS_APP_ID }}
          private-key: ${{ secrets.ISSUEOPS_APP_PEM_FILE }}
          owner: ${{ github.repository_owner }}

      - name: Process IssueOps Request
        id: process
        uses: githubschool/gh-github-intermediate-issueops@main
        with:
          github_token: ${{ steps.token.outputs.token }}
          workspace: ${{ github.workspace }}
